package main;

import java.awt.*;

import javax.swing.JOptionPane;

import threads.*;
import utils.Utils;

/**
 *
 * @author Manulaiko
 */
public class Main extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public Point top, bottom, mTop, mBottom;
	public boolean tIsStopped = false, debug = false, Debug = false, isUpdated = false;
	public int uri, cre, exp, hon, bbCollected = 0;
	public String server = "", sid = "";
	
	public Minimap    mm;
	public WebChecker wc;
	//public Commands   cm = new Commands();
	//public static KeyListener kl = new KeyListener();
	public Thread m, w;
	//public static Thread k;
	
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IBot PB 1.1 by Manulaiko");
        setName("mainForm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(230, 610));

        jLabel1.setText("Username:");

        jTextField1.setEnabled(false);

        jLabel2.setText("Password:");

        jTextField2.setEnabled(false);

        jLabel3.setText("Server:");

        jButton1.setText("Login");
        jButton1.setEnabled(false);

        jLabel4.setText("Session ID:");

        jLabel5.setText("BonusBox delay:");

        jTextField5.setText("1500");

        jLabel6.setText("Minimap delay:");

        jTextField6.setText("20000");

        jButton2.setText("Client top left");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTopLeft(evt);
            }
        });

        jButton3.setText("Client bottom right");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		getBottomRight(evt);
        	}
        });

        jButton4.setText("Minimap top left");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		getMTopLeft(evt);
        	}
        });

        jButton5.setText("Minimap bottom right");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		getMBottomRight(evt);
        	}
        });

        jLabel7.setText("Credits: ");

        jLabel9.setText("Uridium: ");

        jButton6.setText("Start");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		start();
        	}
        });

        jLabel11.setText("Collected BB: ");

        jLabel12.setText("Earned Uridium: ");

        jLabel13.setText("Earned credits: ");

        jButton7.setText("Stop");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		close();
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(jTextField2)
                                    .addComponent(txt)
                                    .addComponent(jTextField4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );

        jLabel8.getAccessibleContext().setAccessibleName("lblCredits");
        jLabel10.getAccessibleContext().setAccessibleName("lblUridium");

        pack();
    }// </editor-fold>                        

    /* Starts point getters */
    private void getTopLeft(java.awt.event.ActionEvent evt) {                                         
        try {
        	JOptionPane.showMessageDialog(null, "Place the mouse in the TOP LEFT corner of the CLIENT and wait 5 seconds...");
            Thread.sleep(5000);
            top = MouseInfo.getPointerInfo().getLocation();
            JOptionPane.showMessageDialog(null, "Done!\nTop left X: "+ top.x +"\nTop left Y: "+ top.y);
        } catch (Exception e) { 
        	JOptionPane.showMessageDialog(null, "Something weird happend, try again...");
        	if(debug) JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void getBottomRight(java.awt.event.ActionEvent evt) {
        try {
        	JOptionPane.showMessageDialog(null, "Place the mouse in the BOTTOM RIGHT corner of the CLIENT and wait 5 seconds...");
            Thread.sleep(5000);
            bottom = MouseInfo.getPointerInfo().getLocation();
            JOptionPane.showMessageDialog(null, "Done!\nBottom right X: "+ bottom.x +"\nBottom right Y: "+ bottom.y);
        } catch (Exception e) { 
        	JOptionPane.showMessageDialog(null, "Something weird happend, try again...");
        	if(debug) JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void getMTopLeft(java.awt.event.ActionEvent evt) {                                         
        try {
        	JOptionPane.showMessageDialog(null, "Place the mouse in the TOP LEFT corner of the CLIENT and wait 5 seconds...");
            Thread.sleep(5000);
            mTop = MouseInfo.getPointerInfo().getLocation();
            JOptionPane.showMessageDialog(null, "Done!\nTop left X: "+ mTop.x +"\nTop left Y: "+ mTop.y);
        } catch (Exception e) { 
        	JOptionPane.showMessageDialog(null, "Something weird happend, try again...");
        	if(debug) JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void getMBottomRight(java.awt.event.ActionEvent evt) {
        try {
        	JOptionPane.showMessageDialog(null, "Place the mouse in the BOTTOM RIGHT corner of the CLIENT and wait 5 seconds...");
            Thread.sleep(5000);
            mBottom = MouseInfo.getPointerInfo().getLocation();
            JOptionPane.showMessageDialog(null, "Done!\nBottom right X: "+ mBottom.x +"\nBottom right Y: "+ mBottom.y);
        } catch (Exception e) { 
        	JOptionPane.showMessageDialog(null, "Something weird happend, try again...");
        	if(debug) JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /* End point getters */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    /**
     * Description:
     * 	Starts pre-botting
     */
    public void start() {
    	//check if everything is setted and correct
    	if(top != null && bottom != null && mTop != null && mBottom != null &&
    	   txt.getText() != null && jTextField4.getText() != null && jTextField5.getText() != null && jTextField6.getText() != null ) {
    		Utils.main = this;
    		Utils.setCenterPoint();
    		
    		try { Thread.sleep(1500); } catch(Exception e) { }
    		if(!server.equals("") && !sid.equals("")) {
    			//if(debug) System.out.println("Starting thread for Apache HTTP library...");
    			w = new Thread(wc);
    			w.start();
    			//if(debug) System.out.println("Starting thread for key event listener...");
    			//k.start();
    			//if(debug) System.out.println("Starting thread for minimap movements...");
    			m = new Thread(mm);
    			m.start();
    			//if(debug) System.out.println("Starting thread for commands collect...");
    			//c = new Thread(cm);
    			//c.start();
    		} else {
    			//System.out.println("Server and sessionID can't be empty!");
    		}
    		run();
    	} else {
    		JOptionPane.showMessageDialog(null, "Something went wrong...");
    	}
    }
    
    /**
     * Description:
     * 	Starts botting :D
     */
	@SuppressWarnings("deprecation")
	public void run()
	{
		try {
			while(true)
			{
				//if(debug) System.out.println("Searching for bonusbox (pixel: 0xDB8742)");
				Point BB = Utils.pixelSearch("0xDB8742", top, bottom);
				
				if(BB != null) {
					if(!tIsStopped) {
						//if(debug) System.out.println("Stopping thread for minimap movements...");
						m.stop();
						tIsStopped = true;
					}
					
					//System.out.println("BonusBox found!");
					//if(debug) System.out.println("X: " + BB.x + " Y: " + BB.y);
					//System.out.println("Collecting bonusbox...");
					Utils.click(BB.x, BB.y);
					//if(debug) System.out.println("Sleeping (1500)");
					Thread.sleep(1500);
					bbCollected++;
				} else {
					//if(debug) System.out.println("BonusBox not found...");
					if(tIsStopped) {
						//if(debug) System.out.println("Starting thread for minimap movements...");
						m = new Thread(mm);
						m.start();
						tIsStopped = false;
					}
				}
				Thread.sleep(150);
			}
		} catch (Exception e) {
			System.out.println("Something weird happened...");
			System.out.println(e.getMessage());
			e.printStackTrace();
		}
	}

    /**
     * Description:
     * 	Stops botting
     */
    public void close() {
    	
    }
    
    /* Start updaters */
    public void updateCredits(long ammount) {
    	
    }
    public void updateUridium(long ammount) {
    	
    }
    public void updateEarnedCredits() {
    	
    }
    public void updateEarnedUridium() {
    	
    }
    public void updateBB() {
    	
    }
    /* End updaters */
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration                   
}
